### ISSUE TITLE
Error Messages for Approvals

### ISSUE THREAD

**Issue by tony-o** [10Kft/10kft-api#10]
I'm the sole user of the account and when I attempt to approve a TimeEntry I receive: `{"message":"forbidden"}`

Is it possible to provide more information about why I can't approve time as an administrator?

**Comment by aatrostle** [comment]
Hey @tony-o Apologies on this delayed response.

As stated in our documentation on [Submitting and Approving Approvables](https://github.com/10Kft/10kft-api/blob/master/sections/approvals.md#submitting-and-approving-approvables)

> Note that only administrators and project managers can approve time and expenses, which means that **API users can only submit time and expenses, but not approve**.

Unfortunately this is currently how the Approvals feature is designed. I hope this helps clarify the error you're seeing.
