### ISSUE TITLE
Unofficial Ruby wrapper

### ISSUE THREAD

**Issue by prehnRA** [10Kft/10kft-api#11]
Hello. Over at Revelry Labs we're happy 10k users. We put together a Ruby wrapper for the API: https://github.com/revelrylabs/tenk

Would you be willing to list this in the API documentation? Also, who should I work with for API questions / issues?

**Comment by shyam-habarakada** [comment]
Hello there. Yes, we would love to. I'll add a section of third party libraries and add yours to the list.

**Comment by shyam-habarakada** [comment]
Added https://github.com/10Kft/10kft-api/blob/master/README.md
