### ISSUE TITLE
Archive / Unarchive User

### ISSUE THREAD

**Issue by thomasmcgee** [10Kft/10kft-api#12]
Hi there, I ran into a problem archiving / unarchiving users.
I was able to archive a user with a PUT along with a json payload like {ID:someID, archived:true}. I thought this was the method used until I looked at the documentation closer and saw that it's supposed to be a GET with archive=true/false

I'm letting you know because I was able to archive the account user with this method, but I was unable to unarchive them, I received an error like "Archived objects cannot be modified".

I thought you'd like to know as someone else may run into the same issue. 

Thanks for the great application and api!

*edit, I just took another look and I'm actually a little confused, GET ?archive=true/false doesn't seem to do anything. PUT ?archived=true/false seems to be the way to go. PUT with a json payload {ID:someID, archived:true} seems to archive a user, but will not unarchive them?

From the Docs:
archive	true to archive/false to unarchive
GET  /api/v1/users/<user_id>
 curl 'https://vnext.10000ft.com/api/v1/users/12345?fields=tags,assignments&auth=...'

**Comment by aatrostle** [comment]
Apologies on the delayed response to this @thomasmcgee 😅 

As you have identified our API documentation is incorrect for `GET v1/users/<id>`, as you describe, you cannot archive/unarchive via `GET`. I will be updating these shortly.

Are you still having issues with unarchiving a user via a `PUT`? You should be able to make the following call to unarchive a user:

```
PUT https://app.10000ft.com/api/v1/users/<id>?archived=false
```

**Comment by thomasmcgee** [comment]
I'm good, no worries, thought you'd like to know.
