### ISSUE TITLE
Golang API

### ISSUE THREAD

**Issue by marwan-at-work** [10Kft/10kft-api#13]
Hi there,
Over at www.work.co, we're beginning to extensively use the 10kft API so I thought I'd share the library we created in Go if you're interested in including it in your 3rd party reference: www.github.com/workco/go-tenkft

We love your product : )

**Comment by aatrostle** [comment]
Apologies for the delay on this @marwan-at-work , I've [added your integration to our API docs](https://github.com/10Kft/10kft-api/blob/master/README.md#third-party-libraries) 🎉
