### ISSUE TITLE
Projects list optional parameters inconsistent with product

### ISSUE THREAD

**Issue by mstoaks** [10Kft/10kft-api#15]
In the projects api, two of the parameters listed in the github API docs:

filter_field: Specifies the property to filter on. "project_state" is the only supported value
filter_list: The value of "filter_field" to match, outputs will be projects with **state** matching this value. Possible values: Internal, Tentative, Confirmed

This means that project_state can only have the values Internal, Tentative or Confirmed.

But, in the product itself, Project State is either Active or Archived. It's actually Project **Type** which can be Internal, Tentative or Confirmed.

Not a huge deal but potentially confusing.

Echoing others... thanks for maintaining this great API, it's been very helpful!

**Comment by aatrostle** [comment]
Thanks for the feedback @mstoaks. Your right, this is potentially confusing. I've registered this issue with the team.

Since the docs are accurate at this time I am going to close this issue.
