### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by mbreton** [10Kft/10kft-api#2]
Hi guys,

We are happy customers of 10kft and we would integrate it to some internal tools. We seen on the README.md that the custom fields is marked as "coming soon". Do you have more informations about that ?

Thanks

**Comment by aatrostle** [comment]
Custom Fields have been released for Pro (and up) plans, unfortunately our documentation is lagging a bit behind.

We are working to get our documentation up to date ASAP and we can let you know here as soon as they are updated. In the meantime, is there a specific question I can help with?

**Comment by mbreton** [comment]
Thank you to respond so fast.

We have an Pro plan on 10kt, and we use the custom fields on ours users. Nevertheless, when we call `https://vnext-api.10000ft.com/api/v1/users/` (for instance on a stagging env)

We have not custom fields in the result. There is a specific way to retrieve the custom fields from a user ?

**Comment by aatrostle** [comment]
You can retrieve custom field values for your users by making the following call:

`GET https://vnext-api.10000ft.com/api/v1/users/<user_id>/custom_field_values`

Thanks for your patience while we get these docs online.

**Comment by aatrostle** [comment]
I realize you may not want to request this on a per user basis. In that case you can pass `custom_field_values` as the `fields` parameter to users index like the following call:

`GET https://vnext-api.10000ft.com/api/v1/users?fields=custom_field_values`

**Comment by aatrostle** [comment]
Hey @mbreton apologies on the late notice 😊 but our [Custom Field docs are online](https://github.com/10Kft/10kft-api/blob/master/sections/custom-fields.md). Feel free to open another issue or reach out to support if you have other questions!

**Comment by mbreton** [comment]
Nice, thanks a lot for your answers :)

>

-- 
 <http://www.js-republic.com>
