### ISSUE TITLE
Fetchin locked projects

### ISSUE THREAD

**Issue by GozuPro** [10Kft/10kft-api#22]
Hey guys, 

I'm building an internal tool to display time entries per project. We have 306 projects returned however, we've noticed locked projects are missing. Is it in purpose ? Does someone have an explanation ? 

This is the code I'm using, please let me know if you notice something wrong :

```
module.exports = Backbone.Collection.extend({		
	url : "https://app.10000ft.com/api/projects",
	initialize:function(){
		this.fetch({
			data : {
				auth : AppModel.get("accessToken"),
				per_page : 8000
			},
			success: function (collection, response) {
				console.log(response)
			}
		});
	}
}
```

Thanks

**Comment by danallison** [comment]
Hi @GozuPro . Sorry for the delayed response. If you include
```
with_archived: true
```
in the data object, that should do the trick.
