### ISSUE TITLE
Select TimeEntries by UpdatedTime

### ISSUE THREAD

**Issue by bigglesandginger** [10Kft/10kft-api#24]
How can I select only the TimeEntries that were updated from a specific date.  Currently I can only get TimeEntries that are for a specific date.  The problem being that to collect new data involves retrieving all the data which seems crazily inefficient and prone to allow DDOS to the 10kft servers.

**Comment by EdgarPost** [comment]
Can't you use the sort_field parameter in combination with sort_order?

`?sort_field=updated&sort_order=descending`

**Comment by danallison** [comment]
Hi @bigglesandginger . Sorry for the delayed response. @EdgarPost is correct. I hope that solved the issue for you.
