### ISSUE TITLE
Retrieving PTO & Holidays / Accounting for Total Work Days

### ISSUE THREAD

**Issue by Jaace** [10Kft/10kft-api#3]
There doesn't currently seem to be a way to access total work days for a specific assignment. The data included in a call to https://app.10000ft.com/api/v1/users/<user_id>/assignments?from=YYYY-MM-DD&to=YYYY-MM-DD doesn't give any information on working days.

Similarly, there doesn't seem to be any information regarding a user's time off if it's blocked out - is that something that would be included soon or is there a way to do that now that isn't documented here?

**Comment by aatrostle** [comment]
Unfortunately our API does not currently return total working days for an assignment as an attribute of our response. To get this value you would need to get the length of the assignment using the `starts_at` and `ends_at` values then subtract any holidays or weekends that may fall within that range.

This is helpful feedback and will be considered in our planning.

To get information about a users blocked out time off you can get the users assignments and check their `assignable_id`'s against the leave types in the account.

**Comment by ericvangeem** [comment]
Glad to see I'm not the only one facing this issue. I was confused when I could not find any way to retrieve the total hours scheduled for an assignment.
