### ISSUE TITLE
Update  fields  project type, code, Client   after create  project

### ISSUE THREAD

**Issue by morahome** [10Kft/10kft-api#36]
‌HI,,

https://github.com/10Kft/10kft-api
I want to  update  this fields:
-project_type
-client 
-code
after  create a project   if  it's possible?

Dear,
Reynald MORADEL

**Comment by shyam-habarakada** [comment]
Hello @morahome — we are migrating away from github issues on this repo so we can manage and support these types of requests via our regular support channel. Would you mind emailing support@10000ft.com with this? 

I can also do that for you, but you'll find it a bit easier to track replies from our team if you initiate the  email yourself. Let me know if you need assistance with this.

Thanks

**Comment by morahome** [comment]
Yes I agree, I also sent an email to the support since I tried again to create a project with project_code, client, project_state
and it works.
my problem is resolved I do not have the answer code 403 anymore.
