### ISSUE TITLE
Include project name in time entry

### ISSUE THREAD

**Issue by Linuus** [10Kft/10kft-api#37]
Hi!

I'm fiddling around with an emacs package for 10kft. The first thing I want to do is generate a table of time entries for the current week, much like the one in the web interface:

![skarmavbild 2018-01-10 kl 20 44 02](https://user-images.githubusercontent.com/379823/34792028-13aa3f22-f647-11e7-8d95-ee4b4eb764ef.png)

When I fetch time entries I get an assignable_id and assignable_type which I can use to fetch the related project to print the name.
If there are many time entries in different projects this may force me to do a lot of requests.

Is there a way to get the project name directly in the time entry response?

**EDIT:**
I can see that's how you do it in the web GUI (lots of XHR requests) as well so I would assume there is no solution to this issue at the moment.

**Comment by aatrostle** [comment]
Hey @Linuus, your assessment is correct. There is no way currently to get the Assignable name while requesting Time Entries.

If you're building something akin to the Time Tracker in Plans, you might consider using the Project or Assignment API's with `to` and `from` param's to help scope, then fetch Time Entries similarly.

Hope this helps!
