### ISSUE TITLE
please add ability to filter projects, users and assignments by tags or other fields (like location)

### ISSUE THREAD

**Issue by aegaas** [10Kft/10kft-api#45]
My organization has multiple locations, and we'd like to build dashboards that display projects per person or people per project by a particular location.

Currently we accomplish this by getting all users, projects, and assignments between 2 dates and then filtering each resources by location (for users) or project tags.

It would save us a lot of pagination and api requests if we could simply filter by location or tags on these endpoints.

**Comment by aatrostle** [comment]
Hey @aegaas, apologies on the delayed response. Beyond what is currently documented, we don't have specific plans we can share on filtering at this time.
