### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by EdgarPost** [10Kft/10kft-api#47]
We are caching a lot of assignments in our database to generate custom statistics, but we often remove assignments in the 10k dashboard. Our database then has old cached entries. To clean this up, we go through all the assignments in our database and check if it's still available in your API and when it isn't, we remove it from our database. This is a long-running script and is not the best way to handle this and is also spamming your API.

Is it possible to enable some kind of webhook for when an assignment has been removed?

**Comment by swordfish444** [comment]
Hi @EdgarPost,

If you haven't already, take a look at our [Zapier integration](https://zapier.com/apps/10000ft/integrations). We offer a variety of webhooks and are continuing to add to the list. As for assignment specific triggers (webhooks), we only offer assignment created and assignment updated at the moment. 

Currently there is no ETA when we will add assignment deleted events. After you've reviewed the zapier triggers, let me know if this will help with your current needs. There are also long-term plans to open up webhooks directly -- without the use of Zapier.

Hope this helps!

**Comment by EdgarPost** [comment]
Hi @swordfish444,

We have looked at the awesome Zapier, but unfortunately does not cover our needs. I guess we'll have to keep using it the way we are now and wait for the public webhooks ;)

Thanks!
