### ISSUE TITLE
Setting Location in API appears to create duplicate Location entries in Web UI

### ISSUE THREAD

**Issue by istacey** [10Kft/10kft-api#51]
I've written a simple console app to set various user properties in bulk that are difficult to change in the existing web UI.

However, when I use my console app to set the Locataion, it appears to be treated as a new value and added to the list within the settings, despite it already existing.

In an attempt to work out which was the version in use, I renamed one of the instances, but now I have..

Khakiv
Khakiv
Khakiv - 22

London
London
London - 22

This makes filtering my team by location almost impossible.

**Comment by thenickcox** [comment]
@istacey Apologies for the delay in looking into this. Can you post the request you're using to set the location for a user?
