### ISSUE TITLE
Update User Image via API

### ISSUE THREAD

**Issue by galenandrew** [10Kft/10kft-api#54]
I'm working on a small integration for our company to automatically update a user's image in 10kft from our primary company directory. However, from the [Users documentation](https://github.com/10Kft/10kft-api/blob/master/sections/users.md#fields) it does not appear this functionality is supported.

Is there any way to do this?

Thank you in advance!!

**Comment by galenandrew** [comment]
Any recommendations here?

**Comment by thenickcox** [comment]
Hi, @galenandrew. We purposely disabled uploading an image via the API for security purposes. As of recently, the only way to upload an image is via the UI.
