### ISSUE TITLE
Allow user authentication

### ISSUE THREAD

**Issue by aborsu** [10Kft/10kft-api#56]
From what I read in the documentation, at the moment only administrator can create tokens and i'm guessing the permissions of the token are equal to that of an administrator.
It would be nice to allow simple users (such as myself) to create a user token, only allowing me the permissions that go with my user.
I would like to automate parts of my workflow, but I'm having issues convincing my manager to give me an administrator token ...

**Comment by swordfish444** [comment]
@aborsu 	Thanks for bringing this to our attention. Fortunately, you can already do what you're asking. To obtain your token, first login at https://app.10000ft.com/si and enter your user credentials. Upon successfully logging into the app you will find your token under the cookie **tenkft-x**. You can then call the api using the permissions associated with your user.
