### ISSUE TITLE
Where to find 'budget' of a project?

### ISSUE THREAD

**Issue by recumbentbirder** [10Kft/10kft-api#61]
In the 'Budget Report' for a project in your GUI, the _budget_ is compared to 'incurred' and 'future scheduled'. -- I might have missed the obvious, but: where do I find the 'budget' of a project? I would have expected it in the general project information like

  https://api.10000ft.com/api/v1/projects/1915507/

but it's not in there.

Any hints, please?

**Comment by thenickcox** [comment]
@recumbentbirder Sorry for the delay. There are 3 types of budgets available for a project: Time & Fees, Time & Fees (Days), and Expenses. You can refer to the budget for a project at the [budget item docs](https://github.com/10Kft/10kft-api/blob/master/sections/budget-items.md#project-budgets).

For the project you're talking about, you'd have to decide whether you want the fee budget (labor * bill rates), the time budget, or the expense budget. Those you'd pass in as the `item_type` parameter:

`GET https://api.10000ft.com/api/v1/projects/1915507/budget_items?item_type=TimeFees&auth=<YOUR_AUTH_TOKEN>`
