### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by ryanbeymer** [10Kft/10kft-api#62]
We are attempting to create a SPA that utilizes the api. 

We have no issues when dev'n locally but once deployed to a site an error is thrown. How have you dealt with CORS errors in the past?  

`
Access to XMLHttpRequest at 'https://vnext-api.10000ft.com/api/v1/users?auth=[REDACTED]' from origin 'https://example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

**Comment by danallison** [comment]
Hello @ryanbeymer . For security reasons, our CORS policy only allows requests from `localhost` or `*.10000ft.com`. To utilize the API in your SPA, you will need to setup a proxy service to relay requests.

**Comment by ryanbeymer** [comment]
@danallison thanks, we were able to get something up and running with [cors-anywhere](https://github.com/Rob--W/cors-anywhere)
